baseURL = "https://www.pwm1991.com"
languageCode = "en-GB"
DefaultContentLanguage = "en"
title = "Pete Martin"
description = "Pete Martin's homepage"
enableRobotsTXT = true
document_title = "Pete Martin"
publishDir = "build"
[pagination]
  pagerSize = 6
  paginatePath = "blog"
disableKinds = ["taxonomy","taxonomyTerm","sitemap"]
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
  [[menu.main]]
    name = "Workouts"
    url = "/workouts"
  [[menu.icons]]
  [[menu.nav]]
    name = "Email"
    url = "mailto:pete@pwm1991.com"
    [menu.nav.params]
      icon = "mail"
  [[menu.nav]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/pwm1991"
    [menu.nav.params]
      icon = "linkedin"
  [[menu.nav]]
    name = "Github"
    url = "https://www.github.com/pwm1991"
    [menu.nav.params]
      icon = "github"
