baseURL = "https://www.pwm1991.com"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Pete Martin"
description = "Pete Martin's homepage"
enableRobotsTXT = true
document_title = "Pete Martin"
publishDir = "docs"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
